"""empty message

Revision ID: 1e54512b4f48
Revises: 
Create Date: 2024-10-29 21:42:54.565604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e54512b4f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pricePerKilo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('pricePerUnit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pricePerPack', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paymentMethodId', sa.Integer(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('paymentAmount', sa.Float(), nullable=True),
    sa.Column('cardNumber', sa.String(length=16), nullable=True),
    sa.Column('cardType', sa.String(length=10), nullable=True),
    sa.Column('cardExpirationDate', sa.Date(), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('bankName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('roleId', sa.Integer(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('dateJoined', sa.Date(), nullable=True),
    sa.Column('departmentId', sa.Integer(), nullable=True),
    sa.Column('discountRate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maxCredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('customerAddress', sa.String(length=500), nullable=True),
    sa.Column('customerBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maxOwing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=True),
    sa.Column('orderStatus', sa.String(length=20), nullable=True),
    sa.Column('orderTotal', sa.Float(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderLine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['item.id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderLine')
    op.drop_table('order')
    op.drop_table('person')
    op.drop_table('payment')
    op.drop_table('item')
    # ### end Alembic commands ###
