"""empty message

Revision ID: 367cf5f8169f
Revises: e987d976bac5
Create Date: 2024-10-23 21:56:37.358571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367cf5f8169f'
down_revision = 'e987d976bac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerAddress', sa.String(length=500), nullable=True),
    sa.Column('customerBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maxOwing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typeId', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('typeId')

    op.drop_table('customer')
    # ### end Alembic commands ###
