"""empty message

Revision ID: 4fa36eed2686
Revises: bb1ee14c0f85
Create Date: 2024-10-28 16:28:58.235745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa36eed2686'
down_revision = 'bb1ee14c0f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paymentMethodId', sa.Integer(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('paymentAmount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditCardPayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardNumber', sa.String(length=16), nullable=True),
    sa.Column('cardType', sa.String(length=10), nullable=True),
    sa.Column('cardExpirationDate', sa.Date(), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debitCardPayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankName', sa.String(length=50), nullable=True),
    sa.Column('cardNumber', sa.String(length=16), nullable=True),
    sa.Column('cardExpirationDate', sa.Date(), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premadeBoxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veggie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporateCustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discountRate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maxCredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minBalance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=True),
    sa.Column('orderStatus', sa.String(length=20), nullable=True),
    sa.Column('orderTotal', sa.Float(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packVeggie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('pricePerPack', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['veggie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unitPriceVeggie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('pricePerUnit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['veggie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weightedVeggie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pricePerKilo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['veggie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderLine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['item.id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderLine')
    op.drop_table('weightedVeggie')
    op.drop_table('unitPriceVeggie')
    op.drop_table('packVeggie')
    op.drop_table('order')
    op.drop_table('corporateCustomer')
    op.drop_table('veggie')
    op.drop_table('premadeBoxes')
    op.drop_table('debitCardPayment')
    op.drop_table('creditCardPayment')
    op.drop_table('payment')
    op.drop_table('item')
    # ### end Alembic commands ###
