"""empty message

Revision ID: 97723b865fd7
Revises: 367cf5f8169f
Create Date: 2024-10-25 23:26:23.245736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97723b865fd7'
down_revision = '367cf5f8169f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
