"""add new table premadeboxitem

Revision ID: bc87063ff41a
Revises: 
Create Date: 2024-10-30 22:22:55.229844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc87063ff41a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premadeBoxItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premadeBoxId', sa.Integer(), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['item.id'], ),
    sa.ForeignKeyConstraint(['premadeBoxId'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderline',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orderId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('itemId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['item.id'], name='orderline_ibfk_1'),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], name='orderline_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orderLine')
    op.drop_table('premadeBoxItem')
    # ### end Alembic commands ###
